version: '2'
services:
  web:
    expose:
      - "8009"
    build: tomcat/.
  httpd:
    volumes:
      - /Users/paritoshanand/Documents/projects/Docker-Httpd-Tomcat/logs:/var/log/apache2
    ports:
      - 80
    build: httpd/.
